

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const FETCH_USER_CHATS = "FETCH_USER_CHATS";
export const REMOVE_USER_CHATS = "REMOVE_USER_CHATS";
export const REMOVE_USERS = "REMOVE_USERS";
export const FETCH_USERS = "FETCH_USERS";
export const APPEND_USER_CHATS = "APPEND_USER_CHATS";
export const USERLIST_SEARCH = "USERLIST_SEARCH";
export const CONVERSATIONLIST_SEARCH = "CONVERSATIONLIST_SEARCH";
// export const REGISTER_SUCCESS = "REGISTER_SUCCESS";