# Generated by Django 4.2.21 on 2025-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chitchat", "0003_remove_user_username_user_is_email_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
