# Generated by Django 4.2.21 on 2025-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chitchat", "0004_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_VERIFIED", "Not Verified"),
                    ("VERIFIED", "Verified"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                ],
                default="NOT_VERIFIED",
                max_length=20,
                null=True,
            ),
        ),
    ]
