# Generated by Django 4.2.21 on 2025-05-09 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chitchat", "0005_remove_user_is_email_verified_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("USER_EMAIL_VERIFICATION", "Email Verification"),
                            ("SET PASSWORD", "Password Reset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
