# Generated by Django 4.2.21 on 2025-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chitchat", "0006_issuedtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuedtoken",
            name="token",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
