# Generated by Django 4.2.21 on 2025-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chitchat", "0007_alter_issuedtoken_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="status",
            new_name="is_online",
        ),
        migrations.AlterField(
            model_name="issuedtoken",
            name="token",
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_VERIFIED", "Not Verified"),
                    ("VERIFIED", "Verified"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("NEW_USER", "New User"),
                ],
                default="NOT_VERIFIED",
                max_length=20,
                null=True,
            ),
        ),
    ]
