# Generated by Django 5.2.1 on 2025-10-07 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chitchat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConversationMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_message_content", models.TextField(blank=True, null=True)),
                ("last_message_timestamp", models.DateTimeField(blank=True, null=True)),
                ("unread_message_count", models.PositiveIntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_metadata",
                        to="chitchat.conversation",
                    ),
                ),
                (
                    "last_message_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_last_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_metadata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Conversation Metadata",
                "verbose_name_plural": "User Conversation Metadata",
                "ordering": ["-last_message_timestamp", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_message_timestamp"],
                        name="chitchat_us_user_id_1649cf_idx",
                    ),
                    models.Index(
                        fields=["user", "is_archived", "-last_message_timestamp"],
                        name="chitchat_us_user_id_5ea56d_idx",
                    ),
                    models.Index(
                        fields=["conversation", "user"],
                        name="chitchat_us_convers_8b7225_idx",
                    ),
                ],
                "unique_together": {("conversation", "user")},
            },
        ),
    ]
